name: apexo
description: "Dental Clinic Management System"
publish_to: "none"

version: 0.7.2

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  http: ^1.2.2
  fluent_ui: 4.13.0
  hive_flutter: ^1.1.0
  intl: 0.20.2
  table_calendar: ^3.1.2
  logging: ^1.2.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  fl_chart: ^0.69.0
  pocketbase: ^0.20.0
  file_picker: ^8.1.3
  qr_flutter: ^4.1.0
  printing: ^5.13.4
  pdf: ^3.11.1
  bidi: ^2.0.12
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.1
  path: ^1.9.0
  http_parser: ^4.0.2
  teeth_selector: ^0.2.2
  package_info_plus: ^8.1.2
  image: ^4.2.0
  sentry_flutter: ^8.12.0
  
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  archive: ^3.6.1
  yaml: ^3.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/images/logo.png
    - assets/images/missing.png
    - assets/fonts/readex.ttf
    - assets/fonts/readex-bold.ttf